packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  fsevents: true
  less: true
  msgpackr-extract: true
  simple-git-hooks: true
  swiper: true
  unrs-resolver: true
