shellEmulator: true

packages:
  - 'apps/*'
  - 'packages/*'

settings:
  autoInstallPeers: true
  excludeLinks: []
  shellEmulator: true
  trustPolicy: no-downgrade

overrides:
  vite: ^8.0.10

allowBuilds:
  esbuild: true
  simple-git-hooks: true
