shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'packages/*'

settings:
  autoInstallPeers: true
  excludeLinks: []
  shellEmulator: true
  trustPolicy: no-downgrade

overrides:
  vite: ^8.0.10

allowBuilds:
  esbuild: set this to true or false
  simple-git-hooks: set this to true or false
