shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'packages/*'

settings:
  autoInstallPeers: true
  excludeLinks: []
  shellEmulator: true
  trustPolicy: no-downgrade

overrides:
  vite: ^8.0.10
